### ISSUE TITLE
About demo data

### ISSUE THREAD

**Issue by hmyh1202** [fanglab/BEAST#1]
Hi,

   Do you have a demo data for analysis and step-by-step anaysis practice.

Thank  you !

**Comment by oliveira-lab** [comment]
Thank you for your message. We are currently working to provide some capsules that can be run on Docker. Some, are already available at https://beast-docs.readthedocs.io/en/latest/usage.html#running-beast-via-docker, and you are more than welcome to test them.
The remaining will be available soon.

Best,
Pedro
